### ISSUE TITLE
direct url path to specific faucets

### ISSUE THREAD

**Issue by brenzi** [edgeware-network/Universal-Hybrid-Substrate-Faucet#31]
It would be great if we could use links to this faucet that directly go to the faucet for our network, like

https://substratefaucet.xyz/paseo/integritee-network

**Comment by ShankarWarang** [comment]
> It would be great if we could use links to this faucet that directly go to the faucet for our network, like
> 
> https://substratefaucet.xyz/paseo/integritee-network

Thank you for the issue. 
We already built this feature based on the feedback given by Alain Brenzikofer from Integritee to @gagan7gb quite a while back.

Here is the direct faucet link for the Integritee's testnet on Paseo:
[https://substratefaucet.xyz/integritee](https://substratefaucet.xyz/integritee)

Encoding of the link is based on the `url` property corresponding to the chain in the [config](https://github.com/edgeware-network/Universal-Hybrid-Substrate-Faucet/blob/main/constants/config.ts) as follows:
`https://substratefaucet.xyz/{url}`

Does this work for you or do you have any specific utility for `https://substratefaucet.xyz/{chainType}/{url}` encoding? @brenzi

**Comment by brenzi** [comment]
thanks, that was my request, didn't see you did it already. nice! thank you
